- README.md
Fix #27 , as well as other attributes' documentations.
NB: to be merged directly to `master` as the fixed doc is already up-to-date with `master` code, and it permit to see the right documentation in the main github page: https://github.com/kuzzleio/kuzzle-common-objects
> Fix Readme with the actual implementation.

- README.md
> rename metadata into volatile (Readme file)

- README.md
- lib/request.js
- package.json
- test/models/requestResponse.test.js
- test/request.test.js
[Full Changelog](https://github.com/kuzzleio/kuzzle-common-objects/compare/3.0.0...3.0.1)
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0-RC10 | 1.0.0-RC10 |
- [ [#37](https://github.com/kuzzleio/kuzzle-common-objects/pull/37) ] Do not add stack in response if NODE_ENV is not development   ([AnthonySendra](https://github.com/AnthonySendra))
---
> Release 3.0.1

- lib/request.js
- test/models/requestResponse.test.js
- test/request.test.js
Reverts kuzzleio/kuzzle-common-objects#37
> Revert "Do not add stack in response if NODE_ENV is not development"

- README.md
- lib/errors/preconditionError.js
- lib/request.js
- package.json
- test/models/requestResponse.test.js
- test/request.test.js
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0-RC10 | 1.0.0-RC10 |
- [ [#51](https://github.com/kuzzleio/kuzzle-common-objects/pull/51) ] Add error preconditionError   ([AnthonySendra](https://github.com/AnthonySendra))
- [ [#50](https://github.com/kuzzleio/kuzzle-common-objects/pull/50) ] Revert "Do not add stack in response if NODE_ENV is not development"   ([AnthonySendra](https://github.com/AnthonySendra))
---
> Release 3.0.2

- lib/errors/index.js
The PreconditionError was not exposed in `lib/errors/index.js`
> Expose PreconditionError constructor

- package.json
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0-RC10 | 1.0.0-RC10 |
- [ [#53](https://github.com/kuzzleio/kuzzle-common-objects/pull/53) ] Expose PreconditionError constructor   ([AnthonySendra](https://github.com/AnthonySendra))
---
> Release 3.0.3

- README.md
- lib/models/requestInput.js
- lib/models/requestResponse.js
- lib/request.js
- lib/utils/assertType.js
- package.json
- test/models/requestInput.test.js
- test/request.test.js
| Kuzzle | Proxy |
|--------|-------|
| 1.0.0-RC9.6 | 1.0.0-RC9 |
---
* [ #56 ]  Add request headers to request.input ([ballinette](https://github.com/ballinette))
> Release 3.0.4

- README.md
- lib/request.js
- test/request.test.js
This method allows to clean the error in request and change a request from error to 200
> Add method clearError in object request

- README.md
- lib/models/requestContext.js
- lib/utils/assertType.js
- package-lock.json
- package.json
- test/models/requestContext.test.js
- test/utils/assertType.test.js
- [ [#67](https://github.com/kuzzleio/kuzzle-common-objects/pull/67) ] Add a context.connection object   ([scottinet](https://github.com/scottinet))
---
> Release 3.0.8

- lib/models/requestContext.js
- lib/models/requestInput.js
- lib/models/requestResponse.js
- lib/request.js
- test/models/requestResponse.test.js
Everything is in the title
```
git clone https://github.com/kuzzleio/kuzzle-common-objects.git
cd kuzzle-common-objects
npm install
node
> const Request = require('.').Request
> let request = new Request({controller: 'controller', action: 'action', index: 'index', collection: 'collection'})
>
> console.log(request)
```
> Make console.log output Request & co

- lib/errors/parseError.js
- lib/models/requestContext.js
- lib/models/requestInput.js
- lib/models/requestResponse.js
- lib/request.js
- package-lock.json
- package.json
- test/models/requestResponse.test.js
- [ [#70](https://github.com/kuzzleio/kuzzle-common-objects/pull/70) ] Add a deprecation jsdoc to the ParseError object   ([scottinet](https://github.com/scottinet))
---
> Release 3.0.11

- lib/models/requestResponse.js
- package-lock.json
- package.json
- test/errors/externalServiceError.test.js
- test/errors/partialError.test.js
- test/models/requestContext.test.js
- test/models/requestInput.test.js
- test/models/requestResponse.test.js
- test/request.test.js
- [ [#76](https://github.com/kuzzleio/kuzzle-common-objects/pull/76) ] Allow setHeader to register lower and uppercase headers   ([Aschen](https://github.com/Aschen))
---
> Release 3.0.14

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- package-lock.json
- package.json
- [ [#78](https://github.com/kuzzleio/kuzzle-common-objects/pull/78) ] Add subcode error and explicit name to KuzzleError   ([Yoann-Abbes](https://github.com/Yoann-Abbes))
---
> Release 3.0.15

- lib/errors/kuzzleError.js
- lib/errors/partialError.js
Do not expose error codes and names yet, this will be done at a later time.
> [revert] do not expose errors code & name just yet

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- test/errors/kuzzleError.test.js
KuzzleError objects are now serialized with the error id and code.
> Error codes support

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- package-lock.json
- package.json
- test/errors/kuzzleError.test.js
- [ [#84](https://github.com/kuzzleio/kuzzle-common-objects/pull/84) ] Error codes support   ([scottinet](https://github.com/scottinet))
---
> Release 4.0.1

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- package-lock.json
- package.json
- test/errors/kuzzleError.test.js
- [ [#86](https://github.com/kuzzleio/kuzzle-common-objects/pull/86) ] Error codes support   ([scottinet](https://github.com/scottinet))
---
> Release 3.0.17

- lib/errors/index.js
- lib/errors/tooManyRequestsError.js
- package-lock.json
- package.json
- [ [#88](https://github.com/kuzzleio/kuzzle-common-objects/pull/88) ] Add a new TooManyRequestsError class (status 429)   ([scottinet](https://github.com/scottinet))
---
> Release 4.1.0

- .mocharc.json
- .travis.yml
- lib/request.js
- package-lock.json
- package.json
- test/mocha.opts
- [ [#93](https://github.com/kuzzleio/kuzzle-common-objects/pull/93) ] Lighter production dependencies   ([scottinet](https://github.com/scottinet))
---
> Release 4.1.1

- lib/models/requestContext.ts
Fix types for `RequestContext` and particularly the `misc` property
> Add connection misc info

- lib/models/requestContext.ts
- package-lock.json
- package.json
- [ [#101](https://github.com/kuzzleio/kuzzle-common-objects/pull/101) ] Add connection misc info   ([Aschen](https://github.com/Aschen))
---
> Release 5.0.1
