- .gitignore
- models/requestObject.js
- package.json
- test/requestObject.test.js
Changed the way that requestObject is builded.
seen with @ballinette 
We need to organize a workshop to speak about refactoring some things on all inputs in kuzzle (there is a lot of divergences)
> remove old behavior on requestobject on request refactor

- models/requestObject.js
- package.json
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
> Update uuid to version 3.0.0

- README.md
- lib/errors/kuzzleError.js
- lib/models/requestContext.js
- lib/models/requestInput.js
- lib/models/requestResponse.js
- lib/request.js
- lib/utils/assertType.js
- package.json
- test/models/requestContext.test.js
- test/models/requestResponse.test.js
- test/request.test.js
- test/utils/assertType.test.js
It turns out using weakMaps to simulate some private properties causes some performance penalty and some memory leak.
=> Removed in favor of plain simple _ prefixed internal vars
This functionality is totally out of the scope of the previous item but was included there as it was quite urgent and would have caused conflict with the previous development.
The Request.response object has been added a `headers` Array property. The idea is that
* For HTTP protocol,  the proxy will treat them as HTTP headers (to be developed)
* Plugins can then add some custom headers like setting some cookies or defining some Content-cache directives.
> Optimizations & Response headers [High priority!!]

- README.md
- lib/models/requestResponse.js
- lib/request.js
- package.json
- test/models/requestResponse.test.js
- test/request.test.js
Pre-requisite for https://github.com/kuzzleio/kuzzle/issues/586
* response format has been changed to avoid naming conflicts with the injected `headers` property inside the returned response content
* add an option to set a raw response, allowing for non-standard Kuzzle response. This has been deemed useful to allow plugins to return responses in other formats than JSON
> kuzzle-#586: dynamic http options

- lib/errors/kuzzleError.js
- lib/errors/pluginImplementationError.js
- lib/models/requestResponse.js
- package.json
- test/request.test.js
Following #14, we missed the fact non http protocols were outputing the content only and still need the status.
The only drawback is that for http, we will get the status twice, once in the http status code and once in the body but this simplifies a lot the rest of the process.
Edit: also fixes #16
> Status needs to be duplicated between the content and the main enveloppe

- codecov.yml
- lib/request.js
- package.json
- test/request.test.js
Pre-requisite to fix the following issue: https://github.com/kuzzleio/kuzzle/issues/591
Add a new property in the `Request` object to allow tracking of triggered events. Will be used by Kuzzle Core to prevent infinite event loops from concurrent plugins API calls.
* make travis use Node 6.x instead of Node 4.x, allowing to use ES6 extensions
* fix codecov reporting
> Track triggered events

- lib/errors/partialError.js
- package.json
- test/errors/partialError.test.js
Add a dedicated serialization method to this object instead of relying only on the one in the abstract `KuzzleError` object.
#20
> [HOTFIX] Fix PartialError objects serialization

- lib/errors/partialError.js
- package.json
- test/errors/partialError.test.js
Add a dedicated serialization method to this object instead of relying only on the one in the abstract `KuzzleError` object.
#20
> Fix PartialError objects serialization

- lib/errors/externalServiceError.js
- test/errors/externalServiceError.test.js
Adds a new error type, to be used to notify Kuzzle and clients about unusual errors coming from external services such as Elasticsearch or Redis.
"Unusual error" == any error which is not a bad request nor a service unavailable error
https://github.com/kuzzleio/kuzzle/issues/731
> Add ExternalServiceError error constructor

- README.md
- lib/request.js
- test/request.test.js
This pull request answers to two needs at once, both for kuzzle plugins executing multiple Kuzzle API actions:
* when a global event is triggered on an API request (such as `request:onError`), plugins handling such events need to know the origin request, and where in the request chain the current request stands
* when a requests chain trigger events, we need to prevent infinite loop to occur. Such a system already exists but there is a case where the current protection does not work (see #24)
* Add a new `origin` property, accepting only a `Request` reference:
* used by Kuzzle to set the starting point of a request chain
* read-only once set
* the setter will get the origin of the provided request reference, and set it as its own request origin
* `request.triggers(event)` now register …
> Keep track of requests chains

- lib/errors/kuzzleError.js
- lib/request.js
- test/models/requestResponse.test.js
- test/request.test.js
Not sending to the user the stack trace if `NODE_ENV` is different than "development". 
The error is still logged in Kuzzle (via `triggerPlugin('log:error')`)
* https://github.com/kuzzleio/kuzzle/issues/747
> Do not add stack in response if NODE_ENV is not development

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- lib/request.js
- test/errors/partialError.test.js
- test/request.test.js
When instanciating a new `Request` object from serialized data, and if an error object is present, then the request constructor throws the following error: `cannot set a non-error object as a request's error`
This PR fixes this problem by instanciating a new `KuzzleError` object prior to setting the error part of the request, when a serialized error has been provided.
* Update error objects to ES6 classes
#59
> Unserialize error objects instead of throwing an exception

- lib/request.js
- package.json
- test/mocha.opts
- test/request.test.js
Currently, `Request` object instances can only be identified using the `requestId` field, a mutable property that can be set by plugins or clients.
Since this is the only available identifier, this can lead to vulnerabilities, for instance in the overload-protection mechanism, where the request identifier is key to manage the requests available slots.
This PR adds a new immutable `internalId` generated by the request constructor, usable by Kuzzle to safely identify a request object internally.
Update dependencies.
> Generate an internal identifier when creating a request object instance

- README.md
- lib/models/requestContext.js
- lib/utils/assertType.js
- package-lock.json
- package.json
- test/models/requestContext.test.js
- test/utils/assertType.test.js
(see [KZL-49](https://jira.kaliop.net/browse/KZL-49))
* Add a `RequestContext.connection` object listing connection properties
* The previous `RequestContext.connectionId` and `RequestContext.protocol` properties have been deprecated, and aliased to the new `RequestContext.connection.id` and `RequestContext.connection.protocol` properties, respectively
* A new `RequestContext.connection.ips` property has been added, which will contain the full list of a client's IP addresses
* A new `RequestContext.connection.misc` object property has been added, meant to host protocol specific information (for instance, the invoked HTTP URL)
Fix https://github.com/kuzzleio/kuzzle/issues/1106
* Replace the obsolete `istanbul` module with its successor, `nyc`
* Add the missing `package-lock.json` file to …
> Add a context.connection object

- .gitignore
- README.md
- lib/models/requestContext.js
- lib/models/requestInput.js
- lib/request.js
- package-lock.json
- package.json
- test/request.test.js
Changes introduced in the 3.0.8 version haven't impacted the serialization method, meaning that serializing/unserializing a `Request` object will not lead to the same content.
This PR fixes that. And since v3.0.8 should not be used in its current state, this PR should be a hotfix.
```
const Request = require('kuzzle-common-objects).Request;
const foo = new Request({}, {
connection: {
id: 'foo', 
protocol: 'bar', 
url: '/foo/bar', 
headers: {foo: 'bar'}, 
ips: ['yolo']
}
});
const serialized = foo.serialize();
const bar = new Request(serialized.data, serialized.options);
console.dir(foo.context.connection.toJSON(), {depth: null});
/*
=> prints:
{ user: null,
token: null,
connection: 
{ id: 'foo',
protocol: 'bar',
ips: [ 'yolo' ],
url: '/foo/bar',
headers: { foo: 'bar' } } }
*/ …
```
> Fix Request serialization

- lib/models/requestContext.js
- package-lock.json
- package.json
The new `RequestContext` version has its `id` and `protocol` properties configured as "writable until a value has been set" (once set, those properties can never be changed).
While this is probably the best course of action regarding those 2 properties, this cause a backward-compatibility problem with pre-1.4.1 versions of Kuzzle, where a coding error in the HTTP embedded protocol first declare a RequestContext with a meaningless connection ID, and then with a connectionId update a bit later. Causing access logs to complain about non-existing connections.
Start a Kuzzle pre-1.4.0 with the 3.0.9 version of this module. Submit any query, and the access log should complain about "a non-existing connection that might have been closed before the query had the chance to be executed" (or …
> Hotfix: connection.id and connection.protocol should not be read-only

- lib/errors/parseError.js
This PR only adds a small jsdoc comment to the `ParseError` object, to remind us that it is deprecated (and since what Kuzzle version)
> add a deprecation jsdoc to the ParseError object

- lib/models/requestResponse.js
- package-lock.json
- test/models/requestResponse.test.js
Even if the RFC specify that header names are case insensitive, we should not force them to lowercase when a user set the response headers.  
This PR allow to set case sensitive header names.
This snippet will result in 2 header different header sent in the response
```
response.setHeader('set-cookie', 'foo=bar')
response.setHeader('Set-Cookie', 'bar=foo')
```
- Step 1 : Use the core plugin boilerplate
- Step 2 : Set responses headers with the same name but in different case
> Allow setHeader to register lower and uppercase headers

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
https://jira.kaliop.net/browse/KZL-1035
This PR is related to this [one](https://github.com/kuzzleio/kuzzle/pull/1306)
:exclamation: Do not merge until the previous one is.
It adds an explicit `name` and error `code` to `KuzzleError`
clone the `kuzzle` repo and go to the `KZL-1035-subcode-error` branch
install this version of `kuzzle-common-objects` module
`npm install git://github.com/kuzzleio/kuzzle-common-objects.git#KZL-1035-subcode-error --save`
Run unit tests
`npm run unit-testing`
> Add subcode error and explicit name to KuzzleError

- lib/models/requestResponse.js
- lib/request.js
- lib/utils/assertType.js
- test/mocha.opts
- test/models/requestResponse.test.js
- test/request.test.js
- test/utils/assertType.test.js
Fix several problems with how response headers are currently handled:
Response headers are currently stored in the `Request` object, but can only be accessed from the `RequestResponse` one. 
This makes it impossible to create a standalone `RequestResponse` object, and I can see no reason to store response headers outside the RequestResponse object.
Response headers are meant to be case-insensitive, while retaining the letter cases used when setting a value to a header.
This is because response headers are meant to be universal, and if HTTP headers are case insensitive, other protocols headers might not be. 
But the current implementation is done in such a way that simply setting the same header with different letter cases leads to duplicate headers. This is a mean bug, as Kuzzle itself …
> Fix response headers

- lib/errors/badRequestError.js
- lib/errors/externalServiceError.js
- lib/errors/forbiddenError.js
- lib/errors/gatewayTimeoutError.js
- lib/errors/internalError.js
- lib/errors/kuzzleError.js
- lib/errors/notFoundError.js
- lib/errors/parseError.js
- lib/errors/partialError.js
- lib/errors/pluginImplementationError.js
- lib/errors/preconditionError.js
- lib/errors/serviceUnavailableError.js
- lib/errors/sizeLimitError.js
- lib/errors/unauthorizedError.js
- test/errors/kuzzleError.test.js
KuzzleError objects are now serialized with the error id and code.
Same changes than in https://github.com/kuzzleio/kuzzle-common-objects/pull/84 except that this version is backward compatible with ALL versions of Kuzzle v1.
> Error codes support

- lib/errors/index.js
- lib/errors/tooManyRequestsError.js
Add a `TooManyRequestsError` class (HTTP status: 429).
This class is meant to be used by the new rate-limit system that will be implemented in Kuzzle Core.
> Add a new TooManyRequestsError class (status 429)

- .mocharc.json
- .travis.yml
- lib/request.js
- package-lock.json
- package.json
- test/mocha.opts
* `eslint` was erroneously listed as a production dependency, instead of a development one
* add a `files` section in `package.json` to push only code files to NPM
1. Pull this branch
1. Start `npm pack` which will create a .tgz file simulating a NPM package
1. Simulate an NPM install with the generated .tgz package in a local directory, using `npm install <path to the .tgz file>`
Result: instead of a node_modules directory weighting 37Mo (w/ 100+ dependencies), the new one weights less than 450Ko, and it has now only 1 dependency (uuid).
* update dependencies:
* uuid has been updated from v3 to v7: code had to be updated too
* replaced the deprecated `test/mocha.opts` file with `.mocharc.json` 
* make travis run with Node.js v12 instead of v6
> Lighter production dependencies

- README.md
- lib/models/requestResponse.js
- lib/request.js
- test/models/requestResponse.test.js
- test/request.test.js
* Adds a `addDeprecation(version, message)`
* Adds corresponding test
* Add corresponding docs
This PR can be use inside a Kuzzle controller to add a deprecation that will be sent via the request response allowing to display deprecation message from an SDK (among other)
- Step 1 : clone the branch
- Step 2 : start a Kuzzle server
- Step 3 :  run 
```js
const { Request } = require('kuzzle-common-objects')
let request = new Request({});
request.addDeprecation('1.0.0', 'You should now use Kuzzle v2')
console.log(request.deprecations) // [{ version: '1.0.0', 'You should now use Kuzzle v2' }]
```
Linked issue: https://github.com/kuzzleio/kuzzle/issues/1661
> Add deprecation notices

- lib/models/requestContext.ts
Since we use the `path` property to define HTTP routes in Kuzzle we should be consistent in the connection information.
Linked PR: https://github.com/kuzzleio/kuzzle/pull/1849
> Deprecate context.connection.misc.url
